<?php //GENERAL JS STARTS ?>
$(document).ready(function(){$('#load_modal').fadeOut(300);});<?php //fadeout loading modal when page is ready ?>
const hu="<?=file_location('home_url','')?>";const dar="<?=file_location('ajax_url','')?>";<?php // declaring locations?>
function loading(s='Loading',t='id',i='sbtn'){let vl= "<span class='j-spinner-border j-spinner-border-sm'style='margin-right:7px;'></span>"+s;if(t==='id'){$('#'+i).html(vl);$('#'+i).prop('disabled',true);}else if(t==='class'){$('.'+i).html(vl);}$('.'+i).prop('disabled',true);}<?php // disable and showing loading when submit ajax is running?>
function r_b(s='Submit',t='id',i='sbtn'){if(t==='id'){$('#'+i).html(s);$('#'+i).prop('disabled',false);}else if(t==='class'){$('.'+i).html(s);$('.'+i).prop('disabled',false);}}<?php //return submit button when ajax fails or done?>
function fail_action(msg='',btn_val='',sel='',btn_id=''){if(msg === ''){msg = "Error occurred while running request";}$('#st').html(r_m(msg));if(btn_id !== ''){r_b(btn_val,sel,btn_id);}alertoff();}<?php //fail action after ajax fail?>
function directResult(s,btn_val,sel=''){if(sel==='class'){$('.'+btn_val).html(s);}else{$('#'+btn_val).html(s);}alertoff();}
function successRedirect(s,btn_val='',sel='',btn_id='',fail=''){if(s.status==='success'){window.location=s.message;}else{if(s.status === 'error'){for(let x in s.errors){$('#'+x).html(s.errors[x]);}}else if(s.status === 'fail'){if(fail===''){$('#st').html(r_m(s.message));}else{$('#st').html(r_m2(s.message));}}r_b(btn_val,sel,btn_id);};alertoff();}
function successAlert(s,btn_val='',sel='',btn_id='',fail=''){if(s.status==='success'){$('#st').html(r_m(s.message));}else{if(s.status === 'error'){for(let x in s.errors){$('#'+x).html(s.errors[x]);}}else if(s.status === 'fail'){if(fail===''){$('#st').html(r_m(s.message));}else{$('#st').html(r_m2(s.message));}}r_b(btn_val,sel,btn_id);};alertoff();}
function successCallback(s,btn_val='',sel='',btn_id='',fail=''){if(s.status !=='success'){if(s.status === 'error'){for(let x in s.errors){$('#'+x).html(s.errors[x]);}}else if(s.status === 'fail'){if(fail===''){$('#st').html(r_m(s.message));}else{$('#st').html(r_m2(s.message));}}r_b(btn_val,sel,btn_id);};alertoff();}
function rvs(str){return str.split("").reverse().join('');}function grn(){return Math.floor(Math.random() * 9) + 1;}function an(str){frt4 = grn()+''+grn()+''+grn()+''+grn();lst3 = grn()+''+grn()+''+grn();return rvs(frt4+str+lst3)}function rn(str){str = ''+str;return rvs(str.slice(3).slice(0,-4));}<?php //reverse string, generate ranndom number, add num and remove number ?>
alertoff();function alertoff(){setTimeout(thealert,5000);}function thealert(){$("#thealert").fadeOut('slow');}<?php //show the return message and hide in 5 secs?>
function r_m(s){if(s.length>0){s=s;}else{s='Error running request';}return "<div style='color:white;'class='j-button alert j-color1 j-container j-padding j-round'id='thealert'>"+s+"</div>";}<?php //return message as alert?>
function r_m2(s){if(s.length>0){s=s;}else{s='Sorry!!!<br>Error occurred while running request, please try again later or reload page';}var err="<div id='return_message_modal'class='j-modal j-modal-click'><div class='j-card-4 j-modal-content j-color4'style='margin-top:200px;'><div class='j-padding'>"+s+"</div><center class='j-padding'><div class='j-clickable j-text-color1 j-round j-border j-border-color1 j-padding'style='width:100%'onclick=$('#return_message_modal').fadeOut('slow');>Close</div></center></div></div>";$('#st').html(err);$('#return_message_modal').fadeIn('slow');}<?php //return message as modal?>
$(document).ready(function(){let ddi = document.getElementById('drpdwnid');let sIp = document.getElementById('sIp');let m = document.getElementsByClassName('j-modal-click');window.onclick = function(e){for(let i = 0; i < m.length; i++){if(e.target == m[i]){m[i].style.display = 'none';}}if(ddi !== null){if(e.target != ddi && e.target != sIp){ddi.style.display = 'none';}}};});<?php //click anywhere to hide modal?>
<?php if(strstr(file_location('home_url',''),'000webhostapp')){ ?>$(document).ready(function(){$('div').last().hide();});<?php } //hide 000webhost advert?>
$('.min-height').css('min-height',$(window).height()+'px');<?php //for min height of the 3 segment?>
$(document).ready(function(){iauulr('all');});function iauulr(v){$.ajax({url:dar+"act/iauulr/"+v})}<?php //onpage load insert the time page load into last refresh db AND // call to insert last refresh with ajax?>