.j-color1,.j-hover-color1:hover{color:white!important;background-color:<?=get_json_data('primary_color','color')?>!important}.j-text-color1,.j-hover-text-color1:hover{color:<?=get_json_data('primary_color','color')?>!important}.j-border-color1,.j-hover-border-color1:hover{border-color:<?=get_json_data('primary_color','color')?>!important}.j-color2,.j-hover-color2:hover{color:#fff!important;background-color:<?=get_json_data('secondary_color','color')?>!important}.j-text-color2,.j-hover-text-color2:hover{color:<?=get_json_data('secondary_color','color')?>!important}.j-border-color2,.j-hover-border-color2:hover{border-color:<?=get_json_data('secondary_color','color')?>!important}.j-color5,.j-hover-color5:hover{color:#fff!important;background-color:#9e9e9e!important}/*gray*/.j-border-color5,.j-hover-border-color5:hover{border-color:#9e9e9e!important}.j-text-color5,.j-hover-text-color5:hover{color:#757575!important}.j-color8,.j-hover-color8:hover{color:#fff!important;background-color:#d1ecf1!important}/*info (light blue)*/.j-text-color8,.j-hover-text-color8:hover{color:#0c5460!important}.j-border-color8,.j-hover-border-color8:hover{border-color:#bee5eb!important}.j-color9,.j-hover-color9:hover{color:#fff!important;background-color:#4CAF50!important}.j-border-color9,.j-hover-border-color9:hover{border-color:#4CAF50!important}.j-text-color9,.j-hover-text-color9:hover{color:#4CAF50!important}
<?php
$mode = get_single_cookie('dark_mode');
if($mode === 'dark'){
$color3 = '#fff';$color4 = "black";$color6 = "#3a3a3a";$color7 = "#f2f2f2";$logo = "logo_dark.png";
?>.j-color3,.j-hover-color3:hover{color:#000!important;background-color:#fff!important}/*white*/.j-text-color3,.j-hover-text-color3:hover{color:#fff!important}.j-border-color3,.j-hover-border-color3:hover{border-color:#fff!important}.j-border-color4,.j-hover-border-color4:hover{border-color:black!important} /*black*/.j-color4,.j-hover-color4:hover{color:white!important;background-color:black!important}.j-text-color4,.j-hover-text-color4:hover{color:black!important}.j-color6,.j-hover-color6:hover{color:#fff!important;background-color:#616161!important}/*light gray*/.j-text-color6,.j-hover-text-color6:hover{color:#3a3a3a!important}.j-border-color6,.j-hover-border-color6:hover{border-color:#616161!important}.j-color7,.j-hover-color7:hover{color:#000!important;background-color:#f2f2f2!important}/*dark gray*/.j-text-color7,.j-hover-text-color7:hover{color:#f2f2f2!important}.j-border-color7,.j-hover-border-color7:hover{border-color:#f2f2f2!important}<?php
}else{
$color3 = 'black';$color4 = "#fff";$color6 = "#f2f2f2";$color7 = "#3a3a3a";$logo = "logo_white.png";
?>.j-border-color3,.j-hover-border-color3:hover{border-color:black!important} /*black*/.j-color3,.j-hover-color3:hover{color:white!important;background-color:black!important}.j-text-color3,.j-hover-text-color3:hover{color:black!important}.j-color4,.j-hover-color4:hover{color:#000!important;background-color:#fff!important}/*white*/.j-text-color4,.j-hover-text-color4:hover{color:#fff!important}.j-border-color4,.j-hover-border-color4:hover{border-color:#fff!important}  .j-color6,.j-hover-color6:hover{color:#000!important;background-color:#f2f2f2!important}/*light gray*/.j-text-color6,.j-hover-text-color6:hover{color:#f2f2f2!important}.j-border-color6,.j-hover-border-color6:hover{border-color:#f2f2f2!important}.j-color7,.j-hover-color7:hover{color:#fff!important;background-color:#616161!important}/*dark gray*/.j-text-color7,.j-hover-text-color7:hover{color:#3a3a3a!important}.j-border-color7,.j-hover-border-color7:hover{border-color:#616161!important}<?php
}
?>